import type { Order } from '@/types';

/** Demo order history. In production this would come from /api/orders. */
export const ORDERS: Order[] = [
  {
    id: 'o1',
    stockId: 'mtnn',
    side: 'Buy',
    type: 'Limit',
    qty: 10,
    price: 275,
    status: 'Open',
    time: 'Today, 11:24 AM',
    fee: 466.5,
    reference: 'SX-ORD-8841',
    cscs: 'CSCS/0123456789',
  },
  {
    id: 'o2',
    stockId: 'gtco',
    side: 'Sell',
    type: 'Market',
    qty: 20,
    price: 53,
    status: 'Completed',
    time: 'Today, 09:10 AM',
    filledPrice: 53.2,
    settlementDate: '28 Aug',
    fee: 142.9,
    reference: 'SX-ORD-8799',
    cscs: 'CSCS/0123456789',
  },
  {
    id: 'o3',
    stockId: 'dangcem',
    side: 'Buy',
    type: 'Limit',
    qty: 50,
    price: 335,
    status: 'Open',
    time: 'Yesterday, 03:48 PM',
    fee: 2261.3,
    reference: 'SX-ORD-8712',
    cscs: 'CSCS/0123456789',
  },
  {
    id: 'o4',
    stockId: 'aapl',
    side: 'Buy',
    type: 'Market',
    qty: 2,
    price: 229.8,
    status: 'Settled',
    time: 'Yesterday, 10:02 AM',
    filledPrice: 229.8,
    settlementDate: '25 Aug',
    fee: 6198.5,
    reference: 'SX-ORD-8655',
    cscs: 'CSCS/0123456789',
  },
  {
    id: 'o5',
    stockId: 'buacement',
    side: 'Sell',
    type: 'Limit',
    qty: 100,
    price: 99,
    status: 'Cancelled',
    time: '21 Aug, 02:15 PM',
    reference: 'SX-ORD-8611',
  },
  {
    id: 'o6',
    stockId: 'jaizbank',
    side: 'Buy',
    type: 'Market',
    qty: 2000,
    price: 6.4,
    status: 'Settled',
    time: '20 Aug, 11:30 AM',
    filledPrice: 6.4,
    settlementDate: '23 Aug',
    fee: 172.8,
    reference: 'SX-ORD-8519',
    cscs: 'CSCS/0123456789',
  },
];

export function getOrders(status: 'All' | Order['status'] = 'All'): Order[] {
  if (status === 'All') return ORDERS;
  return ORDERS.filter((o) => o.status === status);
}
