import { useMemo, useState } from 'react';
import { Modal, Pressable, Share, StyleSheet, Text, View } from 'react-native';
import { Image } from 'expo-image';
import { Ionicons } from '@expo/vector-icons';

import type { TxKind, WalletTransaction } from '@/types';
import { money, mulberry32 } from '@/utils';
import { C, F, R, S } from '@/theme';
import logoApp from '@/assets/images/logo-app.png';

/** Shared transaction-kind metadata (icon + colour + label). */
export const KIND_META: Record<TxKind, { icon: string; color: string; label: string }> = {
  deposit: { icon: 'arrow-down-outline', color: '#0E8A57', label: 'Deposit' },
  withdrawal: { icon: 'arrow-up-outline', color: '#1F7AE0', label: 'Withdrawal' },
  buy: { icon: 'trending-up-outline', color: '#11A06B', label: 'Buy order' },
  sell: { icon: 'trending-down-outline', color: '#F6A623', label: 'Sell order' },
  dividend: { icon: 'cash-outline', color: '#7C5CFF', label: 'Dividend' },
  fee: { icon: 'receipt-outline', color: '#6C7771', label: 'Fees' },
  refund: { icon: 'refresh-outline', color: '#DD4B3E', label: 'Refund' },
};

/** Deterministic fake barcode drawn from the reference string. */
function Barcode({ seed }: { seed: string }) {
  const bars = useMemo(() => {
    let h = 0;
    for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) | 0;
    const rnd = mulberry32(Math.abs(h) || 7);
    return Array.from({ length: 42 }, () => 1 + Math.floor(rnd() * 3));
  }, [seed]);
  return (
    <View style={styles.barcode}>
      {bars.map((w, i) => (
        <View
          key={i}
          style={{
            width: w,
            height: 34,
            backgroundColor: i % 9 === 4 ? 'transparent' : C.ink,
            marginRight: 1 + (i % 3),
          }}
        />
      ))}
    </View>
  );
}

function Row({ label, value, valueColor }: { label: string; value: string; valueColor?: string }) {
  return (
    <View style={styles.row}>
      <Text style={styles.rowLabel}>{label}</Text>
      <Text style={[styles.rowValue, valueColor ? { color: valueColor } : null]}>{value}</Text>
    </View>
  );
}

/**
 * Full-screen transaction receipt with a share button.
 * Share uses the native sheet (RN Share); where that is unavailable
 * (some browsers) the details are copied to the clipboard instead.
 */
export function ReceiptModal({
  tx,
  onClose,
}: {
  tx: WalletTransaction | null;
  onClose: () => void;
}) {
  const [copied, setCopied] = useState(false);
  if (!tx) return null;

  const meta = KIND_META[tx.kind];
  const credit = tx.amount >= 0;
  const statusColor =
    tx.status === 'Completed' ? C.green : tx.status === 'Pending' ? '#F6A623' : C.negative;

  const shareText = [
    'StocksX — Transaction receipt',
    `Reference: ${tx.reference}`,
    `${meta.label}${tx.ticker ? ` · ${tx.ticker}` : ''} · ${tx.status}`,
    `Amount: ${credit ? '+' : '−'}${money(Math.abs(tx.amount))}`,
    tx.note ? `Details: ${tx.note}` : `Method: ${tx.method ?? '—'}`,
    `Balance after: ${money(tx.balanceAfter)}`,
    tx.time,
    '— Generated by StocksX',
  ].join('\n');

  const share = async () => {
    try {
      await Share.share({ message: shareText });
    } catch {
      // native share unavailable (e.g. web without navigator.share) → copy
      try {
        const nav = (globalThis as unknown as { navigator?: { clipboard?: { writeText(t: string): Promise<void> } } }).navigator;
        await nav?.clipboard?.writeText(shareText);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      } catch {
        /* nothing else we can do */
      }
    }
  };

  return (
    <Modal transparent visible animationType="fade" onRequestClose={onClose}>
      <Pressable style={styles.backdrop} onPress={onClose}>
        <Pressable style={styles.card} onPress={() => undefined}>
          {/* header */}
          <View style={styles.head}>
            <Image source={logoApp} style={styles.logo} contentFit="contain" />
            <View style={{ flex: 1 }}>
              <Text style={styles.brand}>StocksX</Text>
              <Text style={styles.brandSub}>Transaction receipt</Text>
            </View>
            <Pressable onPress={onClose} style={styles.closeBtn}>
              <Ionicons name="close" size={18} color={C.muted} />
            </Pressable>
          </View>

          {/* amount */}
          <View style={styles.amountBlock}>
            <View style={[styles.kindChip, { backgroundColor: `${meta.color}16` }]}>
              <Ionicons name={meta.icon as never} size={14} color={meta.color} />
              <Text style={[styles.kindText, { color: meta.color }]}>
                {meta.label}
                {tx.ticker ? ` · ${tx.ticker}` : ''}
              </Text>
            </View>
            <Text style={[styles.amount, { color: credit ? C.positive : C.ink }]}>
              {credit ? '+' : '−'}
              {money(Math.abs(tx.amount))}
            </Text>
            <View style={[styles.statusPill, { backgroundColor: `${statusColor}18` }]}>
              <Text style={[styles.statusText, { color: statusColor }]}>{tx.status}</Text>
            </View>
          </View>

          {/* details */}
          <View style={styles.dash} />
          <Row label="Reference" value={tx.reference} />
          <Row label="Method" value={tx.method ?? '—'} />
          {tx.note ? <Row label="Details" value={tx.note} /> : null}
          <Row label="Balance after" value={money(tx.balanceAfter)} />
          <Row label="Date" value={tx.time} />
          <View style={styles.dash} />

          {/* barcode */}
          <View style={{ alignItems: 'center' }}>
            <Barcode seed={tx.reference} />
            <Text style={styles.code}>{tx.reference}</Text>
          </View>

          {/* actions */}
          <View style={styles.actions}>
            <Pressable onPress={share} style={({ pressed }) => [styles.shareBtn, pressed && { opacity: 0.85 }]}>
              <Ionicons name="share-social-outline" size={16} color={C.white} />
              <Text style={styles.shareBtnText}>{copied ? 'Copied!' : 'Share receipt'}</Text>
            </Pressable>
            <Pressable onPress={onClose} style={({ pressed }) => [styles.doneBtn, pressed && { opacity: 0.85 }]}>
              <Text style={styles.doneBtnText}>Done</Text>
            </Pressable>
          </View>
        </Pressable>
      </Pressable>
    </Modal>
  );
}

const styles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(10,25,18,0.55)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: S.lg,
  },
  card: {
    width: '100%',
    maxWidth: 380,
    backgroundColor: C.white,
    borderRadius: R.xl,
    padding: S.xl,
  },
  head: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  logo: { width: 38, height: 38, borderRadius: 11 },
  brand: { color: C.ink, fontFamily: F.display, fontSize: 17, fontWeight: '800' },
  brandSub: { color: C.muted, fontFamily: F.sans, fontSize: 11.5, marginTop: 1 },
  closeBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: C.canvasAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  amountBlock: { alignItems: 'center', marginTop: S.lg, gap: 7 },
  kindChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: R.pill,
  },
  kindText: { fontFamily: F.sans, fontSize: 12, fontWeight: '700' },
  amount: { fontFamily: F.display, fontSize: 32, fontWeight: '800', letterSpacing: -1 },
  statusPill: { paddingHorizontal: 10, paddingVertical: 3, borderRadius: R.pill },
  statusText: { fontFamily: F.sans, fontSize: 11, fontWeight: '800' },
  dash: {
    borderTopWidth: 1.5,
    borderTopColor: C.hairline,
    borderStyle: 'dashed',
    marginVertical: S.md,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
    gap: 12,
  },
  rowLabel: { color: C.muted, fontFamily: F.sans, fontSize: 12.5 },
  rowValue: {
    color: C.ink,
    fontFamily: F.mono,
    fontSize: 12.5,
    fontWeight: '700',
    flexShrink: 1,
    textAlign: 'right',
  },
  barcode: { flexDirection: 'row', alignItems: 'center', marginTop: 2 },
  code: {
    color: C.faint,
    fontFamily: F.mono,
    fontSize: 10,
    letterSpacing: 2,
    marginTop: 6,
  },
  actions: { flexDirection: 'row', gap: S.sm, marginTop: S.lg },
  shareBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    backgroundColor: C.green,
    paddingVertical: 13,
    borderRadius: R.md,
  },
  shareBtnText: { color: C.white, fontFamily: F.sans, fontSize: 13.5, fontWeight: '800' },
  doneBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.canvasAlt,
    paddingHorizontal: S.lg,
    paddingVertical: 13,
    borderRadius: R.md,
  },
  doneBtnText: { color: C.ink, fontFamily: F.sans, fontSize: 13.5, fontWeight: '700' },
});
